/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppTrendsRouteImport } from './routes/_app.trends'
import { Route as AppSavingsRouteImport } from './routes/_app.savings'
import { Route as AppRecurring_spendingRouteImport } from './routes/_app.recurring_spending'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurring_spendingRoute = AppRecurring_spendingRouteImport.update({
  id: '/recurring_spending',
  path: '/recurring_spending',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/recurring_spending': typeof AppRecurring_spendingRoute
  '/savings': typeof AppSavingsRoute
  '/trends': typeof AppTrendsRoute
  '/trips': typeof AppTripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/recurring_spending': typeof AppRecurring_spendingRoute
  '/savings': typeof AppSavingsRoute
  '/trends': typeof AppTrendsRoute
  '/trips': typeof AppTripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/recurring_spending': typeof AppRecurring_spendingRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/trends': typeof AppTrendsRoute
  '/_app/trips': typeof AppTripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/recurring_spending'
    | '/savings'
    | '/trends'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/recurring_spending'
    | '/savings'
    | '/trends'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/recurring_spending'
    | '/_app/savings'
    | '/_app/trends'
    | '/_app/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring_spending': {
      id: '/_app/recurring_spending'
      path: '/recurring_spending'
      fullPath: '/recurring_spending'
      preLoaderRoute: typeof AppRecurring_spendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppRecurring_spendingRoute: typeof AppRecurring_spendingRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppTripsRoute: typeof AppTripsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppRecurring_spendingRoute: AppRecurring_spendingRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppTripsRoute: AppTripsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
