// Remember to keep front end inline with any changes made here
export enum SpendingCategory {
    AIRFARE = 'AIRFARE',
    BUSINESS = 'BUSINESS',
    CANNABIS = 'CANNABIS',
    CLOTHING = 'CLOTHING',
    DRINKS = 'DRINKS',
    EDUCATION = 'EDUCATION',
    ENTERTAINMENT = 'ENTERTAINMENT',
    EV_CHARGING = 'EV_CHARGING',
    FITNESS = 'FITNESS',
    FUEL = 'FUEL',
    GAMES = 'GAMES',
    GIFTS = 'GIFTS',
    GROOMING = 'GROOMING',
    GROCERIES = 'GROCERIES',
    HEALTH = 'HEALTH',
    HOBBY = 'HOBBY',
    HOUSING = 'HOUSING',
    INSURANCE = 'INSURANCE',
    LODGING = 'LODGING',
    MATERIAL_ITEMS = 'MATERIAL_ITEMS',
    NICOTINE = 'NICOTINE',
    OTHER = 'OTHER',
    PETS = 'PETS',
    RESTAURANTS = 'RESTAURANTS',
    TAXES = 'TAXES',
    TRANSPORTATION = 'TRANSPORTATION',
    TREATS = 'TREATS',
    UTILITIES = 'UTILITIES',
    VEHICLE = 'VEHICLE',
}

// Remember to keep front end inline with any changes made here
export enum AccountCategory {
    CHECKING = 'CHECKING',
    SAVINGS = 'SAVINGS',
    INVESTING = 'INVESTING',
    BONDS = 'BONDS',
}
