const locale = {
  authScreen: {
    welcome: 'Welcome to SpendWatcher',
    email: 'Email address',
    username: 'Username',
    password: 'Password',
    register: 'Register',
    login: 'Login',
    submit: 'Submit',
    invalidCredentials: 'Check your username and password and try again.',
  },
  dashboard: {
    monthOverview: '{{0}} overview',
    totalSpent: 'Total spent',
    discretionaryTotal: 'Discretionary total',
    recurringTotal: 'Recurring total',
    dayOfMonthProgress: 'Day {{0}} of {{1}}',
    percentOfMonth: '{{0}}% of {{1}}',
    onPaceFor: 'On pace for {{0}} this month',
    paceUnder: "{{0}}% under {{1}}'s pace",
    paceOver: "{{0}}% over {{1}}'s pace",
    dailySpendHeading: 'Daily spend — last {{0}} days',
    bigSpikeLabel: 'Big spike · {{0}} — {{1}}',
    todayAxisLabel: 'Today',
    deltaVsPrevMonth: '{{0}}% vs {{1}}',
    flatVsPrevMonth: 'flat vs {{0}}',
    awaitingUpdate: '{{0}} awaiting update',
    topCategories: 'Top discretionary categories',
    avgSpentPerMonth: 'Avg spent · per month',
    vsYearAvg: 'vs {{0}} avg',
  },
  spendingData: {
    topCombined: 'Combined total',
    other: 'Remaining total',
    noTopDiscretionaryCategories: 'You have no discretionary spending so far this month.',
    moreLabel: 'See more',
  },
  navigation: {
    dashboard: 'Dashboard',
    savings: 'Savings',
    trends: 'Trends',
    recurring: 'Recurring',
    recurringDesktop: 'Recurring spending',
    trips: 'Trips',
  },
  trends: {
    pageTitle: 'Trends',
    dashboardButton: 'Dashboard',
    // filterButton: 'Filter', TODO:
    yearlyLabel: 'Yearly',
    monthlyLabel: 'Monthly',
    transactionsTitle: 'Discretionary transactions',
    topCategories: 'Top discretionary categories',
    spendingByCategory: 'Spending by category',
    shareOfTotal: 'Share of total',
    spendingByCategoryEmpty: 'No spending recorded for this period yet.',
    vsPrevMonthHeader: 'vs {{0}}',
    lastSixMonthsHeader: 'Last 6 months',
    monthsInsightLabel: 'Months',
    monthsInsightHeadlinePrefix: '{{0}} was your priciest month — ',
    monthsInsightHeadlineDelta: '{{0}} above',
    monthsInsightHeadlineSuffix: ' average',
    monthsInsightEmpty: 'Not enough history to compare months yet.',
    breakdownInsightLabel: 'Breakdown',
    breakdownInsightHeadlinePair: '{{0}} and {{1}} are {{2}}% of {{3}} so far',
    breakdownInsightHeadlineSingle: '{{0}} is {{1}}% of {{2}} so far',
    breakdownInsightEmpty: 'No spending recorded for this month yet.',
    categoriesInsightLabel: 'Categories',
    categoriesInsightUp: '{{0}} is up {{1}}%',
    categoriesInsightDown: '{{0}} is down {{1}}%',
    categoriesInsightSuffix: ' vs your 3-month average',
    categoriesInsightEmpty: 'Not enough history to compare categories yet.',
    paceInsightLabel: 'Pace',
    paceInsightPrefix: "You're ",
    paceInsightUnder: '{{0}} under',
    paceInsightOver: '{{0}} over',
    paceInsightSuffix: ' your usual pace this month',
    paceInsightProjection: 'Projected {{0}} vs a typical {{1}}',
    paceInsightEmpty: 'Not enough history to know your usual pace yet.',
    rhythmInsightLabel: 'Rhythm',
    rhythmInsightHeadlinePrefix: '{{0}} ran ',
    rhythmInsightHeadlineRatio: '{{0}}× your daily median',
    rhythmInsightCalm: 'No unusual spending days in {{0}} yet.',
    rhythmInsightEmpty: 'Not enough history to know your rhythm yet.',
    spendingByMonthHeading: 'Spending by month',
    spendingByMonthSubheading: 'Last 6 months · select a month to see what drove it',
    spendingByMonthAvgLine: '6-mo avg {{0}}',
    spendingByMonthSoFarSuffix: ' · so far',
    spendingByMonthEmpty: 'Not enough history to compare months yet.',
    selectedMonthLabel: 'Selected month',
    aboveYourAverage: '{{0}} above your average',
    belowYourAverage: '{{0}} below your average',
    whatDroveIt: 'What drove it',
    vsYourAverageMonth: 'vs your average month',
    everythingElseLabel: 'Everything else',
    noTransactionsForMonth: 'No discretionary transactions this month.',
    newCategoryBadge: 'new',
    categoryLedgerHeading: 'Categories',
    categoryLedgerSubheading: '{{0}} vs your 3-month average · biggest movers first',
    avgPerMonth: 'avg {{0}}/mo',
    categoryLedgerTransactionCount: '{{0}} · {{1}} transaction(s)',
    vsThreeMonthAvgSuffix: 'vs your 3-mo average',
    dashedAverageLabel: 'dashed = your average {{0}}',
    transactionsInMonth: 'Transactions in {{0}}',
    newestFirst: 'newest first',
    recurringExcludedNote: 'Recurring bills are excluded — nothing here is a subscription.',
    categoryLedgerEmpty: 'No spending recorded in the last 6 months.',
    category: 'Category',
    totalAmountSpentHeader: 'Total spent',
    totalCountHeader: 'Transaction count',
    totalPercentageHeader: 'Percentage of total',
    totalCountPercentageHeader: 'Percentage of transactions',
    discretionaryTotalHeader: 'Discretionary total',
    discretionaryTotalCountHeader: 'Discretionary transaction count',
    discretionaryTotalPercentageHeader: 'Discretionary % of total',
    discretionaryTotalCountPercentageHeader: 'Discretionary % of transactions',
    recurringTotalHeader: 'Recurring total',
    recurringTotalCountHeader: 'Recurring transaction count',
    recurringTotalPercentageHeader: 'Recurring % of total',
    recurringTotalCountPercentageHeader: 'Recurring % of transactions',
    total: 'Total',
  },
  general: {
    empty: '--',
    submit: 'Submit',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    close: 'Close',
    confirmChange: 'Confirm change',
    mutationErrorTitle: "Couldn't save your changes",
    mutationErrorMessage: 'Check your connection and try again.',
    routeErrorTitle: 'Something went wrong',
    routeErrorMessage: 'Reload the page and try again.',
    reloadPage: 'Reload page',
  },
  savings: {
    pageTitle: 'Savings',
    accountTotalByType: 'Totals by account type',
    netWorth: 'Net worth',
    netWorthAllocationEmpty: 'Add an account with a balance to see your allocation.',
    ytdGrowth: 'YTD growth',
  },
  accounts: {
    addAccount: 'Add account',
    totalAccountValues: 'Accounts total',
    accountNameLabel: 'Account name',
    accountTypeLabel: 'Account type',
    startingAccountValueLabel: 'Current account value',
    annualGrowthRateLabel: 'Annual growth rate',
    fixedRateLabel: 'This growth rate is fixed',
    accountNamePlaceholder: 'Account name',
    submit: 'Submit',
    cancel: 'Cancel',
    amountPlaceholder: '$0.00',
    percentagePlaceholder: '0.00%',
    accountsList: 'Your accounts',
    asOf: 'As of {{0}}',
    manageAccountHeader: 'Manage {{0}}',
    editAccountHeader: 'Edit {{0}}',
    setInactiveHeader: 'Stop tracking this account',
    deleteAccountHeader: 'Delete account',
    editAccountOption: 'Edit account',
    deleteAccountOption: 'Delete account',
    setInactiveOption: 'Stop tracking this account',
    close: 'Close',
    setAccountInactiveTitle: 'Stop tracking "{{0}}"',
    setAccountInactiveDescription:
      'If you have closed this account or otherwise no longer wish to track account values, you can stop tracking it here. This will not delete the account or its data.',
    stopTrackingButton: 'Stop tracking',
    deleteAccountTitle: 'Permanently delete "{{0}}"',
    deleteAccountDescription:
      'This will permanently delete this account and all of its data. If you wish to keep this data, instead consider setting this account as inactive by choosing "I\'ve closed this account".',
    deleteAccountFinalWarning: 'This action cannot be undone.',
    deleteAccountButton: 'Delete account',
    accountsExpectUpdates: '{{0}} account(s) require updates for this month',
    historyHeader: '"{{0}}" history',
    accountHistoryOption: 'History',
    addNewRow: 'Add for {{0}}',
    amountLabel: 'Amount',
    backButton: 'Back',
    accountRequiresUpdateCTA: '{{0}} requires an update',
  },
  transactions: {
    recent: 'Recent transactions',
    noRecentTransactions: 'You do not have any transactions this month.',
    todayLabel: '{{0}} - Today',
    yesterdayLabel: '{{0}} - Yesterday',
    emptyPlaceholder: '--',
    clearSelection: 'Clear selection',
    logExpense: 'Log expense',
    newExpense: 'New expense',
    editExpense: 'Edit expense',
    deleteExpense: 'Permanently delete this expense',
    amountLabel: 'Amount',
    categoryLabel: 'Category',
    notesLabel: 'Notes',
    dateLabel: 'Date of Expense',
    tripLabel: 'Linked Trip',
    notesPlaceholder: 'About your expense',
    amountPlaceholder: '$0.00',
    tripNotice: 'Your current trip, "{{0}}", has already been applied to this transaction.',
  },
  trips: {
    pageLoadingAccessibleText: 'Trips page is loading',
    pageTitle: 'My trips',
    discretionary: 'Discretionary',
    total: 'Total',
    linkedTransactions: 'Linked transactions',
    details: 'Details',
    close: 'Close',
    editTransaction: 'Edit transaction',
    editTripDetails: 'Edit trip details',
    tripsPageErrorTitle: "We couldn't load your trips",
    tripsPageErrorMessage: 'Please try again later.',
    linkedTransactionsErrorTitle: 'Error loading trip transactions',
    linkedTransactionsErrorMessage:
      'We were unable to show you transactions linked to this trip. Please try again later.',
    addTrip: 'Add trip',
    newTrip: 'New trip',
    tripName: 'Trip name',
    tripNamePlaceholder: 'Europe summer trip',
    startDate: 'Start date',
    endDate: 'End date',
    linkedTransactionsEmptyTitle: 'This trip has no linked transactions yet',
    linkedTransactionsEmptyMessage: 'Add transactions to this trip to see them here.',
    deleteTrip: 'Delete {{0}}',
    deleteButtonLabel: 'Permanently delete this trip',
    deleteSpeedBumpHeader: 'Are you sure?',
    deleteSpeedBumpDescription:
      "This will permanently delete this trip, but all linked transactions will remain.  Linked transactions will have their linked trip value set to 'None'.",
  },
  recurringSpending: {
    pageTitle: 'Recurring spending',
    createNew: 'Create recurring expense',
    monthlyTransactions: 'Monthly transactions',
    inactiveTransactions: 'Inactive transactions',
    estimatedMonthlyTotal: 'Estimated monthly total',
    monthActualTotal: `{{0}} actual total`,
    estimatedLabel: 'Estimated: {{0}}',
    fixedLabel: 'Fixed',
    newRecurringExpenseTitle: 'New recurring expense',
    recurringSpendName: 'Expense name',
    newSpendNamePlaceholder: 'Rent payment',
    categoryLabel: 'Category',
    variableExpenseLabel: 'This amount varies',
    variableExpenseDescription: 'The amount of this expense varies from month to month, like a utility bill.',
    monthlyAmountLabel: 'Monthly amount',
    monthlyAmountVariesLabel: 'Estimated monthly amount',
    monthlyAmountPlaceholder: '$0.00',
    deleteSpeedBumpHeader: 'Are you sure?',
    deleteSpeedBumpDescription:
      'This will permanently delete this recurring expense and all of its past data. This means all previous months\' spend data for "{{0}}" will be permanently deleted.',
    finalDeletionWarning: 'This action cannot be undone.',
    edit: 'Edit',
    transactionHistory: 'History',
    permanentlyDelete: 'Permanently delete',
    cancel: 'Cancel',
    chooseOption: 'What would you like to do?',
    editingTransaction: 'Edit "{{0}}"',
    deletingTransaction: 'Delete "{{0}}"',
    markActive: 'Reactive this expense',
    markInactive: 'Mark as inactive',
    setActiveTitle: 'Reactivate this recurring spend',
    setActiveDescription:
      'Reactivating an expense means fixed expenses will resume being automatically logged each month and variable expenses will remind you to provide a monthly update.  Upon activation, the expense will be logged, or an update requested, for the current month.',
    setInactiveTitle: 'Deactivate this recurring spend',
    setInactiveDescription:
      'Deactivating an expense will stop it from being automatically logged each month, if fixed, or requesting monthly updates, if variable. You can reactivate it at any time.',
    historyTitle: '"{{0}}" history',
    spendsRequiringUpdates: '{{0}} recurring expense(s) require updates this month',
    updateRequired: 'Update required',
  },
  recurringTransactionsList: {
    amountSpentLabel: 'Amount spent',
    backButton: 'Back',
    addNewRow: 'Add for {{0}}',
  },
  ACCOUNT_CATEGORIES: {
    CHECKING: 'Checking',
    SAVINGS: 'Savings',
    INVESTING: 'Investment',
    BONDS: 'Bonds',
  },
  SPENDING_CATEGORIES: {
    RESTAURANTS: 'Dining out',
    DRINKS: 'Drinks',
    GROCERIES: 'Groceries',
    ENTERTAINMENT: 'Entertainment',
    EV_CHARGING: 'EV charging',
    TRANSPORTATION: 'Transportation',
    VEHICLE: 'Vehicle',
    FUEL: 'Fuel',
    FITNESS: 'Fitness',
    GROOMING: 'Grooming & self-care',
    BUSINESS: 'Business expense',
    MATERIAL_ITEMS: 'Material items',
    AIRFARE: 'Airfare',
    LODGING: 'Lodging',
    HEALTH: 'Healthcare',
    CLOTHING: 'Clothing',
    GIFTS: 'Gifts & charity',
    EDUCATION: 'Education',
    UTILITIES: 'Utilities',
    HOUSING: 'Housing',
    CANNABIS: 'Cannabis',
    PETS: 'Pets',
    INSURANCE: 'Insurance',
    NICOTINE: 'Nicotine',
    GAMES: 'Games',
    HOBBY: 'Hobbies',
    TREATS: 'Treats',
    TAXES: 'Taxes',
    OTHER: 'Other',
  },
} as const;

export default locale;
